apiVersion: v1
kind: Service
metadata:
  name: inference-service-nodeport  # Changed the name to distinguish it
  namespace: modeling
spec:
  type: NodePort
  selector:
    app: inference-pod
  ports:
    - protocol: TCP
      port: 8000         # The port exposed externally (can be different if needed)
      targetPort: 8000  # The port your application listens on inside the Pod
      nodePort: 30080   # The port on each node (choose a port between 30000-32767)